// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// NOTE: This file will be overwritten by `flutterfire configure`.
/// Run that command after creating your new Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'run flutterfire configure to set up.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZyQQ7ptEQfUL7QPhw7HgmTWYyQUiHew',
    appId: '1:304917805175:android:fb423a61bcba6fd275ae72',
    messagingSenderId: '304917805175',
    projectId: 'kecdrives-fcm',
    storageBucket: 'kecdrives-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9TLkQQgltGLQBJi2tkocSW31z16GAgk',
    appId: '1:304917805175:ios:40eba97f36bf986275ae72',
    messagingSenderId: '304917805175',
    projectId: 'kecdrives-fcm',
    storageBucket: 'kecdrives-fcm.firebasestorage.app',
    iosBundleId: 'com.kec.student.studentApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83tv5sZzRWGr-gkA_PXV-PLNkFiITV70',
    appId: '1:304917805175:web:20700134c088253a75ae72',
    messagingSenderId: '304917805175',
    projectId: 'kecdrives-fcm',
    authDomain: 'kecdrives-fcm.firebaseapp.com',
    storageBucket: 'kecdrives-fcm.firebasestorage.app',
    measurementId: 'G-EHZN9PEZXJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9TLkQQgltGLQBJi2tkocSW31z16GAgk',
    appId: '1:304917805175:ios:40eba97f36bf986275ae72',
    messagingSenderId: '304917805175',
    projectId: 'kecdrives-fcm',
    storageBucket: 'kecdrives-fcm.firebasestorage.app',
    iosBundleId: 'com.kec.student.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC83tv5sZzRWGr-gkA_PXV-PLNkFiITV70',
    appId: '1:304917805175:web:d694c6ea764a051f75ae72',
    messagingSenderId: '304917805175',
    projectId: 'kecdrives-fcm',
    authDomain: 'kecdrives-fcm.firebaseapp.com',
    storageBucket: 'kecdrives-fcm.firebasestorage.app',
    measurementId: 'G-KRTWCYWSYY',
  );
}
