// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/logout": {
            "post": {
                "description": "Logout user (symbolic in JWT)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with email, password and role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User Registration Details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/applications/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the status of a student application (shortlisted, placed, rejected)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update Application Status",
                "parameters": [
                    {
                        "description": "Status Update Data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/auth/login": {
            "post": {
                "description": "Authenticate admin user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Auth"
                ],
                "summary": "Admin Login",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginInput"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/admin/drives": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all drives without restriction",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "List all placement drives for admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PlacementDrive"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a drive with attachments",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a new placement drive",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drive Data JSON",
                        "name": "drive_data",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Attachments",
                        "name": "attachments",
                        "in": "formData"
                    }
                ],
                "responses": {}
            }
        },
        "/v1/admin/drives/bulk-delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete multiple drives by IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Bulk Delete Drives",
                "parameters": [
                    {
                        "description": "List of Drive IDs",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "format": "int64"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/drives/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing drive details (Admin only). Supports multipart/form-data for adding files.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update a placement drive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Updated Drive Data JSON (if multipart)",
                        "name": "drive_data",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "New Attachments (if multipart)",
                        "name": "attachments",
                        "in": "formData"
                    },
                    {
                        "description": "Updated Drive Data (if json)",
                        "name": "drive",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.CreateDriveInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a drive by ID (Admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete a placement drive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/drives/{id}/add-student": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin forces a student registration for a drive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Manually add a student to a drive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ManualRegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/drives/{id}/applicants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch all students applied to a specific drive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Drive Applicants",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DriveApplicant"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/spocs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a new Single Point of Contact",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spocs"
                ],
                "summary": "Create a new SPOC",
                "parameters": [
                    {
                        "description": "SPOC Details",
                        "name": "spoc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateSpocInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Spoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/spocs/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update SPOC details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spocs"
                ],
                "summary": "Update SPOC",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SPOC ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SPOC Details",
                        "name": "spoc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateSpocInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Spoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a SPOC by ID",
                "tags": [
                    "Spocs"
                ],
                "summary": "Delete SPOC",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SPOC ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/spocs/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Activate or deactivate a SPOC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spocs"
                ],
                "summary": "Toggle SPOC Status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SPOC ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Spoc"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of students with optional filtering by department, batch, or search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "List Students",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department Code",
                        "name": "dept",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Batch Year",
                        "name": "batch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search Term (Name/RegNum)",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin manually adds a student to the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create Student",
                "parameters": [
                    {
                        "description": "Student Details",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateStudentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students/bulk": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete multiple students based on department and batch year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Bulk Delete Students",
                "parameters": [
                    {
                        "description": "JSON with department and batch_year",
                        "name": "filters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students/bulk-upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a CSV file to add multiple students at once",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Bulk Upload Students",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students/delete-many": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete multiple students using their IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Bulk Delete Students by IDs",
                "parameters": [
                    {
                        "description": "List of Student IDs",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "format": "int64"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch full profile of a student by ID or Register Number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Student Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID or Register Number",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentFullProfile"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a student by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete Student",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/students/{student_id}/documents/{type}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a temporary presigned URL for accessing any student's documents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Student Document URL (Admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student User ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "resume",
                            "aadhar",
                            "pan",
                            "profile_photo"
                        ],
                        "type": "string",
                        "description": "Document Type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{id}/block": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Block or Unblock a user to prevent login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Block/Unblock User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Block status {block: true/false}",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Authenticate student user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student Auth"
                ],
                "summary": "Student Login",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginInput"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/brands/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Search for companies/brands by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Brands"
                ],
                "summary": "Search Brands",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/brands/{domain}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch company details like logo and name from Logo.dev",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Brands"
                ],
                "summary": "Get Brand Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Domain (e.g. google.com)",
                        "name": "domain",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/drives": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of drives with optional filtering by department and batch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drives"
                ],
                "summary": "List placement drives for students",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Batch Year",
                        "name": "batch",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PlacementDrive"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/drives/{id}/apply": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows a student to apply for a specific placement drive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application"
                ],
                "summary": "Apply for a Placement Drive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/drives/{id}/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows a student to withdraw (opt-out) from a drive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Application"
                ],
                "summary": "Withdraw application for a Placement Drive",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/spocs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all Single Points of Contact",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spocs"
                ],
                "summary": "List all SPOCs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Spoc"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/student/documents/{type}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a temporary presigned URL for accessing student documents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Get Document URL",
                "parameters": [
                    {
                        "enum": [
                            "resume",
                            "aadhar",
                            "pan",
                            "profile_photo"
                        ],
                        "type": "string",
                        "description": "Document Type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/student/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get full profile details of the logged-in student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Get My Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentFullProfile"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update student profile information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Update Profile",
                "parameters": [
                    {
                        "description": "Profile Data",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/student/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload student documents like Resume, Aadhar, Pan Card etc. to MinIO S3 Storage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Upload Document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document Type (resume, aadhar, pan, profile_pic)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/user/fcm-token": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the Firebase Cloud Messaging token for push notifications",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Update FCM Token",
                "parameters": [
                    {
                        "description": "FCM Token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Attachment": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.CreateDriveInput": {
            "type": "object",
            "required": [
                "company_name",
                "job_role"
            ],
            "properties": {
                "aggregate_percentage": {
                    "type": "number"
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Attachment"
                    }
                },
                "company_category": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "ctc_display": {
                    "type": "string"
                },
                "ctc_max": {
                    "type": "integer"
                },
                "ctc_min": {
                    "type": "integer"
                },
                "deadline_date": {
                    "type": "string"
                },
                "drive_date": {
                    "type": "string"
                },
                "drive_type": {
                    "type": "string"
                },
                "eligible_batches": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "eligible_departments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "job_description": {
                    "type": "string"
                },
                "job_role": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "logo_url": {
                    "description": "[NEW]",
                    "type": "string"
                },
                "max_backlogs_allowed": {
                    "type": "integer"
                },
                "min_cgpa": {
                    "description": "Eligibility",
                    "type": "number"
                },
                "pg_min_cgpa": {
                    "type": "number"
                },
                "rounds": {
                    "description": "Rounds \u0026 Attachments",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Round"
                    }
                },
                "spoc_id": {
                    "description": "[NEW]",
                    "type": "integer"
                },
                "stipend_max": {
                    "type": "integer"
                },
                "stipend_min": {
                    "type": "integer"
                },
                "tenth_percentage": {
                    "description": "Additional Academic Eligibility",
                    "type": "number"
                },
                "twelfth_percentage": {
                    "type": "number"
                },
                "ug_min_cgpa": {
                    "type": "number"
                },
                "use_aggregate": {
                    "type": "boolean"
                },
                "website": {
                    "description": "[NEW]",
                    "type": "string"
                }
            }
        },
        "models.CreateSpocInput": {
            "type": "object",
            "required": [
                "designation",
                "email",
                "mobile_number",
                "name"
            ],
            "properties": {
                "designation": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CreateStudentInput": {
            "type": "object",
            "required": [
                "batch_year",
                "department",
                "email",
                "full_name",
                "mobile_number",
                "register_number"
            ],
            "properties": {
                "batch_year": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "password": {
                    "description": "Optional, default will be used if empty",
                    "type": "string"
                },
                "register_number": {
                    "type": "string"
                }
            }
        },
        "models.DriveApplicant": {
            "type": "object",
            "properties": {
                "applied_at": {
                    "type": "string"
                },
                "cgpa": {
                    "type": "number"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "register_number": {
                    "type": "string"
                },
                "resume_url": {
                    "type": "string"
                },
                "status": {
                    "description": "'opted_in', 'shortlisted', 'placed', 'rejected'",
                    "type": "string"
                },
                "student_id": {
                    "type": "integer"
                }
            }
        },
        "models.LoginInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.ManualRegisterInput": {
            "type": "object",
            "properties": {
                "student_id": {
                    "type": "integer"
                }
            }
        },
        "models.PlacementDrive": {
            "type": "object",
            "properties": {
                "aggregate_percentage": {
                    "type": "number"
                },
                "applicant_count": {
                    "description": "[NEW] Computed field",
                    "type": "integer"
                },
                "attachments": {
                    "description": "JSONB",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Attachment"
                    }
                },
                "company_category": {
                    "description": "'Core', 'IT', 'Service', 'Product', 'Start-up', 'MNC'",
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ctc_display": {
                    "type": "string"
                },
                "ctc_max": {
                    "type": "integer"
                },
                "ctc_min": {
                    "description": "Financials",
                    "type": "integer"
                },
                "deadline_date": {
                    "type": "string"
                },
                "drive_date": {
                    "description": "Dates",
                    "type": "string",
                    "example": "2026-05-20"
                },
                "drive_type": {
                    "description": "Filters \u0026 Categories",
                    "type": "string"
                },
                "eligible_batches": {
                    "description": "JSONB",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "eligible_departments": {
                    "description": "JSONB",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "job_description": {
                    "type": "string"
                },
                "job_role": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "logo_url": {
                    "description": "[NEW]",
                    "type": "string"
                },
                "max_backlogs_allowed": {
                    "type": "integer"
                },
                "min_cgpa": {
                    "description": "Eligibility",
                    "type": "number"
                },
                "pg_min_cgpa": {
                    "type": "number"
                },
                "posted_by": {
                    "type": "integer"
                },
                "rounds": {
                    "description": "Rounds",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Round"
                    }
                },
                "spoc_id": {
                    "description": "[NEW] Single Point Of Contact ID",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "stipend_max": {
                    "type": "integer"
                },
                "stipend_min": {
                    "type": "integer"
                },
                "tenth_percentage": {
                    "description": "Additional Academic Eligibility",
                    "type": "number"
                },
                "twelfth_percentage": {
                    "type": "number"
                },
                "ug_min_cgpa": {
                    "type": "number"
                },
                "use_aggregate": {
                    "type": "boolean"
                },
                "user_status": {
                    "description": "[NEW] For student response ('opted_in', etc.)",
                    "type": "string"
                },
                "website": {
                    "description": "[NEW]",
                    "type": "string"
                }
            }
        },
        "models.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "student",
                        "admin"
                    ]
                }
            }
        },
        "models.Round": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "\"2026-05-21\"",
                    "type": "string"
                },
                "description": {
                    "description": "\"Online test via Hackerearth\"",
                    "type": "string"
                },
                "name": {
                    "description": "\"Aptitude\", \"Technical\", \"HR\"",
                    "type": "string"
                }
            }
        },
        "models.Spoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "designation": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "mobile_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.StudentFullProfile": {
            "type": "object",
            "properties": {
                "aadhar_card_url": {
                    "type": "string"
                },
                "about_me": {
                    "type": "string"
                },
                "batch_year": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "current_backlogs": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "diploma_mark": {
                    "type": "number"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "description": "Personal Info",
                    "type": "string"
                },
                "gap_reason": {
                    "type": "string"
                },
                "gap_years": {
                    "type": "integer"
                },
                "gender": {
                    "type": "string"
                },
                "history_of_backlogs": {
                    "type": "integer"
                },
                "id": {
                    "description": "User Info",
                    "type": "integer"
                },
                "is_blocked": {
                    "type": "boolean"
                },
                "language_skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "last_login": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "pan_card_url": {
                    "type": "string"
                },
                "pg_cgpa": {
                    "type": "number"
                },
                "placement_willingness": {
                    "type": "string"
                },
                "profile_photo_url": {
                    "type": "string"
                },
                "register_number": {
                    "type": "string"
                },
                "resume_url": {
                    "description": "Documents (URLs)",
                    "type": "string"
                },
                "social_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                },
                "student_type": {
                    "type": "string"
                },
                "tenth_mark": {
                    "description": "Academics",
                    "type": "number"
                },
                "twelfth_mark": {
                    "type": "number"
                },
                "ug_cgpa": {
                    "type": "number"
                }
            }
        },
        "models.UpdateProfileInput": {
            "type": "object",
            "properties": {
                "aadhar_card_url": {
                    "type": "string"
                },
                "about_me": {
                    "description": "Personal Identity",
                    "type": "string"
                },
                "city": {
                    "description": "Address",
                    "type": "string"
                },
                "current_backlogs": {
                    "type": "integer"
                },
                "diploma_institution": {
                    "type": "string"
                },
                "diploma_mark": {
                    "type": "number"
                },
                "diploma_year_pass": {
                    "type": "integer"
                },
                "dob": {
                    "type": "string"
                },
                "gap_reason": {
                    "type": "string"
                },
                "gap_years": {
                    "type": "integer"
                },
                "history_of_backlogs": {
                    "type": "integer"
                },
                "language_skills": {
                    "description": "e.g. [\"English\", \"Tamil\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mobile_number": {
                    "type": "string"
                },
                "pan_card_url": {
                    "type": "string"
                },
                "pg_cgpa": {
                    "type": "number"
                },
                "placement_willingness": {
                    "type": "string"
                },
                "profile_photo_url": {
                    "type": "string"
                },
                "resume_url": {
                    "description": "Documents",
                    "type": "string"
                },
                "social_links": {
                    "description": "Skills \u0026 Flexible Data",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                },
                "tenth_board": {
                    "type": "string"
                },
                "tenth_institution": {
                    "type": "string"
                },
                "tenth_mark": {
                    "description": "Academic Updates",
                    "type": "number"
                },
                "tenth_year_pass": {
                    "type": "integer"
                },
                "twelfth_board": {
                    "type": "string"
                },
                "twelfth_institution": {
                    "type": "string"
                },
                "twelfth_mark": {
                    "type": "number"
                },
                "twelfth_year_pass": {
                    "type": "integer"
                },
                "ug_cgpa": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "placement-portal-kec.onrender.com",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Placement Portal KEC API",
	Description:      "API for KEC Placement Portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
